### ISSUE TITLE
Use of Travis CI logo

### ISSUE THREAD

**Issue by ctrlaltjustine** [Yaowenjie/travis-github-chrome-extension#1]
Hello 👋,

My name is Justine and I'm the designer at Travis CI. First of all, I wanted to thank you for reaching out to us about your Chrome extension. It's very awesome and we love that you've created it!

Unfortunately, your Chrome extension for Travis CI is using our logo which is against our branding policies for 3rd party applications as you can find listed here https://travis-ci.org/logo:

> Use the logo for your own company or application icon

This is not to say you may not continue to run your Chrome extension, but we'd like to request you please discontinue use of our logo since the extension is not affiliated with Travis CI.

Thanks so much for being a member of our community and your understanding,
If you have any questions at all please let me know!

Justine

**Comment by Yaowenjie** [comment]
Hi @saltinejustine ,

First of all, thank you for your concern and reminding. Sorry for against the branding policies,  I used it, just since I found some existed extensions with Travis CI's logo.

I'll change the logo of my chrome extension to move your logo out soon, once that done, I'll let you know.

Thanks

**Comment by ctrlaltjustine** [comment]
@Yaowenjie thank you for your understanding and addressing it! We were all impressed with your extension!

**Comment by Yaowenjie** [comment]
@saltinejustine Thanks, I have changed the logo, but it will take several minutes to publish it. Hope you guys at Travis-CI like the extension. :) 

BTW, it's midnight in China now, good night/morning/afternoon for your timezone~

**Comment by ctrlaltjustine** [comment]
Thanks again @Yaowenjie!
