### ISSUE TITLE
Feature Request: to add Dark theme support (or switch button)

### ISSUE THREAD

**Issue by JimmyLv** [Yaowenjie/travis-github-chrome-extension#14]
![image](https://cloud.githubusercontent.com/assets/4997466/22450137/972e8c2a-e79f-11e6-83c3-4a6e8d1f14df.png)

**Comment by Yaowenjie** [comment]
Note: it is mainly for `Github Dark` in [Stylish](https://userstyles.org/styles/37035/github-dark)

**Comment by JimmyLv** [comment]
Cool~

**Comment by JimmyLv** [comment]
![image](https://cloud.githubusercontent.com/assets/4997466/22877937/a4df5e4e-f212-11e6-9a1b-97568f843812.png)

好像矫枉过正了，我的 GitHub 网页 Header 咋都是黑色了呢？

**Comment by JimmyLv** [comment]
Sorry, 原来是在 A/B 测试，ref: [Github "dark mode" header – Designer News](https://www.designernews.co/stories/80122-github-dark-mode-header)

**Comment by Yaowenjie** [comment]
哈哈哈

**Comment by EthanLin-TWer** [comment]
也不是 A/B 测试

> dark mode is here to stay

**Comment by Yaowenjie** [comment]
@linesh-simplicity 👍
