### ISSUE TITLE
Add switch button

### ISSUE THREAD

**Issue by Yaowenjie** [Yaowenjie/travis-github-chrome-extension#2]
Not sure which kind will be better:
1. turn off button 
2. switch chart style

**Comment by EthanLin-TWer** [comment]
implement both and try out/ ab testing

**Comment by Yaowenjie** [comment]
@linesh-simplicity haha, great!

**Comment by Yaowenjie** [comment]
closed by this [PR](https://github.com/Yaowenjie/travis-github-chrome-extension/pull/10)
