### ISSUE TITLE
CSP error log in browser console when switch tabs in github

### ISSUE THREAD

**Issue by Yaowenjie** [Yaowenjie/travis-github-chrome-extension#21]
As below screenshot saying:

<img width="1182" alt="1" src="https://cloud.githubusercontent.com/assets/9637652/22885578/f6204a9e-f234-11e6-8b91-272eec832454.png">

**Comment by Yaowenjie** [comment]
any idea or experience on it? @JimmyLv @linesh-simplicity

**Comment by EthanLin-TWer** [comment]
nope. 

* is it something caused by your plugin? 
* is it something prevents you from switching the tabs or any activities on github?
* why are we using English?

**Comment by Yaowenjie** [comment]
@linesh-simplicity 
1. yes, indeed, this is why I create issue here. It should be caused by the second time API call.
2. It should be the CSP (Content Security Policy).
3. for practice, `Habit makes things natural`. But 中文也是OK的，哈哈哈

**Comment by Yaowenjie** [comment]
Raised a question on [stackoverflow](http://stackoverflow.com/questions/42409877/console-show-csp-error-because-chrome-extension-reload-blob-file-when-location-c)

**Comment by Yaowenjie** [comment]
One thought is that store the svg locally, and judge the state according to [travis api](https://docs.travis-ci.com/api#repositories). It might related to #17.

**Comment by EthanLin-TWer** [comment]
Guiling 他们最近好像也有在做 CSP 相关的事情。

**Comment by Yaowenjie** [comment]
@linesh-simplicity 这个好像和一般的CSP还不太一样，chrome插件的沙盒模型和github本身的CSP，其实我也没搞得特别清楚。
