### ISSUE TITLE
Chart header toggle hiding feature would not be initialized in specific situation 

### ISSUE THREAD

**Issue by Yaowenjie** [Yaowenjie/travis-github-chrome-extension#22]
e.g. if you start from https://github.com/Yaowenjie/travis-github-chrome-extension/projects, then you click `Code` link to access code page, you would find that Chart header toggle hiding feature isn't initialized, so you cannot click it to hide the chart.

**Comment by EthanLin-TWer** [comment]
赞一个，看这英语竟然觉得很顺畅，以后是外国人给你留的评论

**Comment by Yaowenjie** [comment]
@linesh-simplicity 这个repo貌似都有两三个外国友人路过了，请参考 #1 #9 #13 
hahaha

**Comment by EthanLin-TWer** [comment]
#13 那个人家说的那么好你居然没回复…

**Comment by Yaowenjie** [comment]
@linesh-simplicity 之前一直没时间做来着（羞愧脸，其实是`懒`）。你去看看我最新的PR，发布之后会回复的，哈哈哈。
